var skillList=[
	{"des":"AIX"},{"des":"Apple"},{"des":"DOS"},{"des":"FreeBSD"},{"des":"HP-UX"},{"des":"IDMS"},{"des":"Linux"},{"des":"Mac OS"},{"des":"Mac/Macintosh"},{"des":"Mainframe"},{"des":"Microsoft SmartPhone"},{"des":"NDS/Novell Directory Services"},{"des":"Novell"},{"des":"OS X"},{"des":"OS/2"},{"des":"OS/390"},{"des":"OS/400"},{"des":"Palm OS"},{"des":"SCO UNIX"},{"des":"Shell"},{"des":"Solaris"},{"des":"SUN OS"},{"des":"Sun Solaris"},{"des":"Symbian S60"},{"des":"Tandem"},{"des":"TK"},{"des":"TSO"},{"des":"TSO/ISPF"},{"des":"UNIX"},{"des":"VMS"},{"des":"WIN CE"},{"des":"Windows 2000"},{"des":"Windows 2003"},{"des":"Windows 95"},{"des":"Windows 98"},{"des":"Windows Mobile"},{"des":"Windows NT"},{"des":"Windows Vista"},{"des":"Windows 7"},{"des":"Windows Server 2008"},{"des":"Android"},{"des":"iOS"},{"des":"Windows 8"},{"des":"Windows Server 2012"},{"des":"Windows XP"},{"des":"ABAQUS"},{"des":"DDK"},{"des":"MCU"},{"des":"OOAD"},{"des":"OOP"},{"des":"Oracle Forms"},{"des":"PVCS"},{"des":"SDLC"},{"des":"Servlets"},{"des":"STL"},{"des":"Systems Administration"},{"des":"Systems Analysis"},{"des":"Systems Analyst"},{"des":"UML"},{"des":"VxWorks"},{"des":"A+"},{"des":"ActionScript"},{"des":"ADA"},{"des":"AJAX"},{"des":"ASP"},{"des":"ASP.NET"},{"des":"ATL"},{"des":"C"},{"des":"C#"},{"des":"C++"},{"des":"C++.Net"},{"des":"CGI"},{"des":"Clipper"},{"des":"COBOL"},{"des":"COM/DCOM"},{"des":"COOL:Gen"},{"des":"CORBA"},{"des":"Delphi"},{"des":"Developer/ Designer 2000"},{"des":"DirectX"},{"des":"FORTRAN"},{"des":"Fox Pro"},{"des":"FoxBASE+"},{"des":"Infobasic"},{"des":"Java"},{"des":"JCL"},{"des":"JCreator Pro"},{"des":"JMS"},{"des":"JSF"},{"des":"JSP"},{"des":"Kylix"},{"des":"Lotus Notes"},{"des":"LotusScript"},{"des":"Matlab"},{"des":"MFC"},{"des":"PAL"},{"des":"Pascal"},{"des":"PECL"},{"des":"PeopleCode"},{"des":"Perl"},{"des":"PHP"},{"des":"PL/1"},{"des":"PowerBuilder"},{"des":"Pro*C"},{"des":"Python"},{"des":"Rexx"},{"des":"RMI"},{"des":"RPG"},{"des":"Ruby"},{"des":"Simula"},{"des":"SIR"},{"des":"Smalltalk"},{"des":"Spring"},{"des":"SQR"},{"des":"StarTeam"},{"des":"Struts"},{"des":"TCL"},{"des":"VBA"},{"des":"Visual Basic"},{"des":"Visual Basic .net"},{"des":"Visual C#"},{"des":"Visual C++"},{"des":"Visual J#"},{"des":"Visual J++"},{"des":"Visual SourceSafe"},{"des":"Visual Studio"},{"des":"Visual Studio .net"},{"des":"Win32"},{"des":"WinForm"},{"des":"WML"},{"des":"XSL"},{"des":"XSLT"},{"des":"LabVIEW"},{"des":"Silverlight"},{"des":"Objective-C"},{"des":"Adabas"},{"des":"ADO"},{"des":"ANSI SQL"},{"des":"Brio"},{"des":"Capacity Planning"},{"des":"CMMS"},{"des":"Cognos"},{"des":"Data Guard"},{"des":"Data Modeling"},{"des":"Database Administrator"},{"des":"Database Management"},{"des":"DataStage"},{"des":"DB2"},{"des":"Dbase"},{"des":"Endevor"},{"des":"ERwin"},{"des":"Essbase"},{"des":"ETL"},{"des":"FoWindows Xpro"},{"des":"FoxBase"},{"des":"FoxPro 2"},{"des":"IMS"},{"des":"Informix"},{"des":"Informatica"},{"des":"Ingres"},{"des":"Interbase"},{"des":"ISPF"},{"des":"Jasmine"},{"des":"JDBC"},{"des":"Access"},{"des":"MS SQL"},{"des":"MySQL"},{"des":"ODBC"},{"des":"OLAP"},{"des":"Oracle"},{"des":"OWB"},{"des":"ParaDox"},{"des":"PL/SQL"},{"des":"PostgreSQL"},{"des":"Progress"},{"des":"RDBMS"},{"des":"Sagent"},{"des":"SAPDB"},{"des":"Sybase"},{"des":"SYSBASE"},{"des":"Toad"},{"des":"Visual Foxpro"},{"des":"AS/400"},{"des":"BizTalk"},{"des":"CC Mail"},{"des":"CICS"},{"des":"Citrix"},{"des":"ClearCase"},{"des":"ClearQuest"},{"des":"Domino"},{"des":"FileNet"},{"des":"Focus"},{"des":"Hyperion (Brio)"},{"des":"Microsoft Exchange"},{"des":"Microsoft SharePoint"},{"des":"MQSeries"},{"des":"Silverstream"},{"des":"Tomcat"},{"des":"Vmware"},{"des":"VSAM"},{"des":"WebLogic"},{"des":"WebMethods"},{"des":"WebSphere"},{"des":"ActiveX"},{"des":"Apache SOAP"},{"des":"Cold Fusion"},{"des":"DHTML"},{"des":"Dreamweaver"},{"des":"EJB"},{"des":"Electronic Payment"},{"des":"Fireworks"},{"des":"FrontPage"},{"des":"GoLive"},{"des":"HTML"},{"des":"J2EE"},{"des":"J2ME"},{"des":"J2SE"},{"des":"JavaScript"},{"des":"NetObjects Fusion"},{"des":"RoboHelp"},{"des":"SGML"},{"des":"Shtml"},{"des":"SMIL"},{"des":"VBScript"},{"des":"VRML"},{"des":"Web Master/Developer"},{"des":"XHTML"},{"des":"XML"},{"des":"XML Web services"},{"des":"XSP"},{"des":"jQuery"},{"des":"Flex"},{"des":"AdvanceLink"},{"des":"Asynch"},{"des":"Banyan"},{"des":"Banyan Vines"},{"des":"Bay"},{"des":"Bay Networks"},{"des":"BGP"},{"des":"Bridges"},{"des":"BroadVision"},{"des":"Checkpoint"},{"des":"Cisco"},{"des":"DHCP"},{"des":"DNS"},{"des":"e-commerce"},{"des":"EDI"},{"des":"Ethernet"},{"des":"Firewall"},{"des":"Frame Relay"},{"des":"FTP"},{"des":"HP Open View"},{"des":"HTTP"},{"des":"Hubs"},{"des":"Hubs/ Routers"},{"des":"IDS"},{"des":"IIS"},{"des":"Intrusion"},{"des":"iptables"},{"des":"ISAM"},{"des":"ISAPI"},{"des":"ISDN"},{"des":"ISIS"},{"des":"Juniper"},{"des":"LAN"},{"des":"LanManager"},{"des":"LanServer"},{"des":"Lantastic"},{"des":"Lap Link"},{"des":"LDAP"},{"des":"Lease Lines"},{"des":"Load Balancing"},{"des":"MOM"},{"des":"MPLS"},{"des":"Multinet"},{"des":"MVX"},{"des":"NatMaster"},{"des":"Netbios"},{"des":"NetMaster"},{"des":"NetWare"},{"des":"Network Cards"},{"des":"Optical Fibre"},{"des":"OSPF"},{"des":"Pathworks"},{"des":"PPPoE"},{"des":"Reflection"},{"des":"RIP"},{"des":"Routers"},{"des":"SAN"},{"des":"Security"},{"des":"SNA"},{"des":"Sniffer"},{"des":"SOAP"},{"des":"Socket"},{"des":"Sonet"},{"des":"Squid"},{"des":"ssh"},{"des":"TCP/IP"},{"des":"TcpDump"},{"des":"UDP"},{"des":"VLAN"},{"des":"VPN"},{"des":"WAN"},{"des":"WAP"},{"des":"X.25"},{"des":"X400"},
];

function showMe(){
	console.log(skillList[0].des);
}

/*
{"des":"辦公室應用類"},

						{"des":"Adobe Acrobat"},
						{"des":"Communicator"},
						{"des":"Excel"},
						{"des":"ForeHelp"},
						{"des":"Ghost"},
						{"des":"Internet Explorer"},
						{"des":"Lotus 123"},
						{"des":"Netscape Communication"},
						{"des":"OneNote"},
						{"des":"Oracle Financials"},
						{"des":"Outlook"},
						{"des":"PowerPoint"},
						{"des":"Project"},
						{"des":"Publisher"},
						{"des":"Visio"},
						{"des":"Word"},
						{"des":"Wordperfect"},
						{"des":"WPS"},
					]},,
			{"des":"排版軟體類"},

						{"des":"FrameMaker"},
						{"des":"Adobe InDesign"},
						{"des":"Pagemaker"},
						{"des":"QuarkXPress"},
						{"des":"北大方正"},
					]},,
			{"des":"中╱英文打字"},

						{"des":"中文打字20以下"},
						{"des":"中文打字20~50"},
						{"des":"中文打字50~75"},
						{"des":"中文打字75~100"},
						{"des":"中文打字100~125"},
						{"des":"中文打字125~150"},
						{"des":"中文打字150以上"},
						{"des":"英文打字20以下"},
						{"des":"英文打字20~50"},
						{"des":"英文打字50~75"},
						{"des":"英文打字75~100"},
						{"des":"英文打字100~125"},
						{"des":"英文打字125~150"},
						{"des":"英文打字150以上"},
					]},
			]},,
			{"des":"多媒體設計類"},			
					{"des":"3ds Max"},
					{"des":"After Effects"},
					{"des":"Alias"},
					{"des":"Alias studio"},
					{"des":"Authorware"},
					{"des":"CADAM"},
					{"des":"Cakewalk"},
					{"des":"Dimensions 3D"},
					{"des":"Director"},
					{"des":"Flash"},
					{"des":"Freehand"},
					{"des":"Games"},
					{"des":"Graphics"},
					{"des":"HomeSite"},
					{"des":"IconWorkshop"},
					{"des":"Image/Imaging"},
					{"des":"Lightwave"},
					{"des":"Macromedia Director"},
					{"des":"MAYA"},
					{"des":"Microsoft Photo Editor"},
					{"des":"Motion Builder"},
					{"des":"Multimedia Builder"},
					{"des":"Painter"},
					{"des":"Premiere"},
					{"des":"Quark Express"},
					{"des":"Rhino"},
					{"des":"Shockwave"},
					{"des":"Softimage"},
					{"des":"Strata"},
					{"des":"Streamline"},
					{"des":"Vegas"},
					{"des":"Vizact 2000"},
					{"des":"Shade"},
					{"des":"Cinema 4D"},
					{"des":"Showcase"},
					{"des":"3ds Max Design"},
					{"des":"Unity3D"},
				},,
		{"des":"影像處理類"},
				
					{"des":"Adobe Photoshop"},
					{"des":"CoolDraw"},
					{"des":"CorelDraw"},
					{"des":"Illustrator"},
					{"des":"ImageReady"},
					{"des":"Paint Shop Pro"},
					{"des":"PhotoImpact"},
				},,
		{"des":"工程製圖類"},
					{"des":"AutoCAD"},
					{"des":"AutoCad 2D"},
					{"des":"AutoCad 3D"},
					{"des":"Catia"},
					{"des":"iDeaS"},
					{"des":"LightsCape"},
					{"des":"MicroStation"},
					{"des":"Pro/E"},
					{"des":"Revit"},
					{"des":"Sketch up"},
					{"des":"SolidWorks"},
					{"des":"Unigraphics"},
					{"des":"Zbrush"},
					{"des":"Solid Edge"},
					{"des":"Inventor"},
					{"des":"DIALux"},
					{"des":"Photopia"},
				]},
			},,
			{"des":"地理資訊類"},
					{"des":"ArcGis"},
					{"des":"ArcView"},
					{"des":"GIS"},
					{"des":"MapBasic"},
					{"des":"MapInfo"},
					{"des":"MapGIS"},
					{"des":"MapPoint"},
					{"des":"SuperGIS"},
					{"des":"SuperPad"},
				},,
			{"des":"通訊傳輸類"},
					{"des":"3G"},
					{"des":"ADSL"},
					{"des":"AppleTalk"},
					{"des":"Avaya"},
					{"des":"Bluetooth"},
					{"des":"CDMA"},
					{"des":"CIP"},
					{"des":"FDDI"},
					{"des":"FPT"},
					{"des":"GMS"},
					{"des":"GPRS"},
					{"des":"GSM"},
					{"des":"MMS"},
					{"des":"PABX"},
					{"des":"PBX"},
					{"des":"PHS"},
					{"des":"PSTN"},
					{"des":"Relay Gold"},
					{"des":"RF"},
					{"des":"RTSP"},
					{"des":"SMS"},
					{"des":"SNMP"},
					{"des":"SS7"},
					{"des":"Telecom"},
					{"des":"USB OTG"},
					{"des":"VoIP"},
					{"des":"Wimax"},
					{"des":"WLAN"},
					{"des":"XDSL"},
				},,
			{"des":"測試╱安全"},
					{"des":"ACT"},
					{"des":"Astra LoadTest"},
					{"des":"Astra QuickTest"},
					{"des":"Attoltestware"},
					{"des":"BounderChecker"},
					{"des":"Bugzilla"},
					{"des":"C++test"},
					{"des":"Cantata"},
					{"des":"CodeTest"},
					{"des":"DevPartner Studio"},
					{"des":"DriverStudio"},
					{"des":"EcoScope"},
					{"des":"e-Test suite"},
					{"des":"GammaRay"},
					{"des":"HttpUnit"},
					{"des":"IPS"},
					{"des":"Jtest"},
					{"des":"Junit"},
					{"des":"Link Sleuth"},
					{"des":"LoadRunner"},
					{"des":"LogiScope"},
					{"des":"Macabe"},
					{"des":"Mantis"},
					{"des":"OpenSTA"},
					{"des":"Optimizeit Suite"},
					{"des":"PC—lint"},
					{"des":"PureCoverage"},
					{"des":"PVCS Tracker"},
					{"des":"QADirector"},
					{"des":"QALoad"},
					{"des":"QARun"},
					{"des":"QATester"},
					{"des":"QTP"},
					{"des":"Quality Control"},
					{"des":"QuickTest Professional"},
					{"des":"Rational ClearCase"},
					{"des":"Rational ClearQuest"},
					{"des":"Rational Performance"},
					{"des":"Rational PureCoverage"},
					{"des":"Rational Purify"},
					{"des":"Rational Quantify"},
					{"des":"Rational Robot"},
					{"des":"Rational Rose"},
					{"des":"Rational SQA load"},
					{"des":"Rational TeamTest"},
					{"des":"Rational Test RealTime"},
					{"des":"Rational TestFactory"},
					{"des":"Rational TestManager"},
					{"des":"Robot"},
					{"des":"SilkPerformer"},
					{"des":"SilkPlan Pro"},
					{"des":"SilkRadar"},
					{"des":"SilkTest"},
					{"des":"SilkVision"},
					{"des":"Source Safe/Visual Source Safe"},
					{"des":"Test Scripts"},
					{"des":"TestBed"},
					{"des":"TestBytes"},
					{"des":"TestDirector"},
					{"des":"TestManager"},
					{"des":"TestPartner"},
					{"des":"TestQuestPro"},
					{"des":"TestTrack Pro"},
					{"des":"TrackRecord"},
					{"des":"TrueCoverage"},
					{"des":"TrueTime"},
					{"des":"Version Control"},
					{"des":"VisualTest"},
					{"des":"WAS"},
					{"des":"WebFT"},
					{"des":"WebLoad"},
					{"des":"WinRunner"},
					{"des":"XDE Tester"},
					{"des":"Xrunner"},
				},,
			{"des":"資料倉儲"},
					{"des":"CASE"},
					{"des":"Data Architect"},
					{"des":"Data Marts"},
				},,
			{"des":"資訊管理類"},
					{"des":"CleverPath"},
					{"des":"CVS"},
					{"des":"MicroStrategy"},
					{"des":"PeopleSoft"},
					{"des":"RACF"},
					{"des":"Remedy"},
					{"des":"SAN/NAS"},
					{"des":"SAS"},
					{"des":"Siebel"},
					{"des":"SPSS"},
					{"des":"Teradata"},
					{"des":"TIBCO"},
					{"des":"Tivoli"},
					{"des":"VERITAS"},
				]},
			},,
			{"des":"設計類"},
					{"des":"ADC"},
					{"des":"ARM"},
					{"des":"ASIC"},
					{"des":"Assembly"},
					{"des":"AVL"},
					{"des":"CA"},
					{"des":"Cadence Allegro"},
					{"des":"Chipware"},
					{"des":"Circuit Design"},
					{"des":"CPLD"},
					{"des":"DEC/VAX"},
					{"des":"Drivers"},
					{"des":"DSP"},
					{"des":"EDA"},
					{"des":"EMC/EMI"},
					{"des":"Firmware"},
					{"des":"FPGA"},
					{"des":"GEAC"},
					{"des":"LCOS"},
					{"des":"MicroFocus"},
					{"des":"MIDI"},
					{"des":"Mobile Network"},
					{"des":"MVS"},
					{"des":"OrCAD"},
					{"des":"PADS"},
					{"des":"P-CAD"},
					{"des":"PLC"},
					{"des":"PLD"},
					{"des":"PowerLogic"},
					{"des":"PowerPCB"},
					{"des":"Protel"},
					{"des":"RTL"},
					{"des":"SPICE"},
					{"des":"Synopsys"},
					{"des":"Tape Operator"},
					{"des":"USB技術"},
					{"des":"Verilog"},
					{"des":"VHDL"},
					{"des":"VM"},
				},,
			{"des":"產品類"},
					{"des":"DAB數位音頻廣播"},
					{"des":"DSC數位攝像機"},
					{"des":"DVB數位視頻廣播"},
					{"des":"DVR數位視頻錄像"},
					{"des":"GPS全球定位系統"},
					{"des":"Mobile phone"},
					{"des":"PDA/Handhelds"},
					{"des":"WVR無線視頻錄影"},
				]},
			},,
			{"des":"品保類"},
					{"des":"6 Sigma"},
					{"des":"BS7799"},
					{"des":"HACCP"},
					{"des":"ISO14000"},
					{"des":"ISO9000"},
					{"des":"OHSAS18000"},
					{"des":"QS9000"},
					{"des":"RoHS"},
					{"des":"SPC"},
					{"des":"TS16949"},
				},,
			{"des":"製程類"},
					{"des":"CAM"},
					{"des":"CIM"},
					{"des":"CMP化學機械研磨技術"},
					{"des":"CVD化學氣象沉積"},
					{"des":"Flip Chip構裝製程"},
					{"des":"IE工業工程"},
					{"des":"MES"},
					{"des":"PCBA"},
					{"des":"SMT"},
				]},
			},,
			{"des":"ERP"},
					{"des":"ACL"},
					{"des":"Baan"},
					{"des":"Great Plains"},
					{"des":"Lawson"},
					{"des":"MRP"},
					{"des":"Multi Term"},
					{"des":"Navision"},
					{"des":"Oracle ERP"},
					{"des":"QAD－MFG/PRO"},
					{"des":"SSA-BPCS"},
					{"des":"Swift"},
					{"des":"用友U8"},
					{"des":"金蝶"},
					{"des":"浪潮"},
					{"des":"SAP"},
					{"des":"鼎新"},
					{"des":"正航"},
					{"des":"天心資訊"},
					{"des":"文中系統"},
				},,
*/